Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -43,25 +43,24 @@ jobs:
         run: echo "TAG_NAME=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
   
       - name: Create Release
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          REPO: ${{ github.repository }}
+          TAG_NAME: ${{ env.TAG_NAME }}
         id: create_release
         run: |
-          # Create a new release
-          curl -X POST \
-            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
+          RELEASE_RESPONSE=$(curl -s -X POST \
+            -H "Authorization: token $GITHUB_TOKEN" \
             -H "Content-Type: application/json" \
-            -d '{
-              "tag_name": "${{ env.TAG_NAME }}",
-              "target_commitish": "main",
-              "name": "${{ env.TAG_NAME }}",
-              "body": "Release description",
-              "draft": false,
-              "prerelease": true
-            }' \
-            https://api.github.com/repos/${{ github.repository }}/releases \
-            | tee release_response.json
-      
-          # Extract the release ID
-          RELEASE_ID=$(jq -r '.id' release_response.json)
+            -d "{\"tag_name\": \"$TAG_NAME\", \"name\": \"$TAG_NAME\", \"draft\": false, \"prerelease\": false}" \
+            "https://api.github.com/repos/$REPO/releases")
+
+          RELEASE_ID=$(echo $RELEASE_RESPONSE | jq -r '.id')
+
+          if [ "$RELEASE_ID" == "null" ]; then
+            echo "Failed to create a release. Response: $RELEASE_RESPONSE"
+            exit 1
+          fi
       
           for file in ./out/*.img.xz; do
             curl -X POST \
